= Dateien und Dokumente

Wenn für die Pflege von Dokumenten, die einem Objekt zugeordnet werden, keine Funktionen wie die Versionierung, der Freigabeworkflow oder komplexere Ordnerstrukturen benötigt werden, bieten sich die Module Datei und Dokumente an.

Dateien:: 

Das Modul Dateien ermöglicht es Dateien dem Objekt zuzuordnen. Die Liste beinhaltet den Dateinamen, das Datum der Zuordnung, die Anzahl der Downloads (D/L), sowie die sha256 Prüfsumme. Über eine Tooltip wird eine Dateibeschreibung, die beim Upload erfasst wird, dargestellt. +
+
Falls es sich um eine txt oder csv Datei, kann man auch in einem Editor, den man durch Doppelklick auf den Dateinamen erreicht, die Datei bearbeiten.

Dokumente:: 

Das Modul Dokumente bietet die Möglichkeit Dokumente dem Objekt zuzuordnen. Dokumente sind charakterisiert durch
- eine Dokumentenkategorie (Kategorien können über die Administration angepasst werden),
- eine Dokumentenbeschreibung und
- eine oder mehrere zugeordnete Dateien (mit einer Dateibeschreibung).

+
Die Liste der Dokumente lässt sich nach der Dokumentenkategorie, dem Zuordnungsdatum, dem Dokumententitel oder dem Autor (Benutzer der das Dokument angelegt hat) gruppieren. + 
 + 
Die Dateien können heruntergeladen werden. Textdateien (z.B. txt oder csv) lassen sich über einen Editor ändern.