= Dateien und Dokumente

Wenn für die Pflege von Dokumenten, die einem Objekt zugeordnet werden, keine Funktionen wie die Versionierung, der Freigabeworkflow oder komplexere Ordnerstrukturen benötigt werden, bieten sich die xmera Omnia Module _Datei_ und _Dokumente_ an.

Dateien:: 

Das Modul Dateien ermöglicht es, einem Objekt Dateien zuzuordnen. Die Liste beinhaltet den Dateinamen, das Datum der Zuordnung, die Anzahl der Downloads (D/L), sowie die sha256 Prüfsumme. Über eine Tooltip wird eine Dateibeschreibung, die beim Upload erfasst wird, dargestellt. +
+
Inhalte einfacher Textdateien können direkt am Bildschirm gelesen werden.

Dokumente:: 

Das Modul _Dokumente_ bietet die Möglichkeit, einem Objekt eine oder mehrere Dokumentensammlungen zuzuordnen. Eine Dokumentensammlung wird charakterisiert durch

- eine Dokumentenkategorie (Kategorien können über die Administration angepasst werden),
- eine Dokumentenbeschreibung und
- eine oder mehrere zugeordnete Dateien (mit einer Dateibeschreibung).

+
Die Dokumentensammlungen lassen sich nach der Dokumentenkategorie, dem Zuordnungsdatum, dem Dokumententitel oder dem Autor (Benutzer der das Dokument angelegt hat) gruppieren. + 
 + 
Dokumente können heruntergeladen werden. Inhalte einfacher Textdokumente können direkt am Bildschirm gelesen werden.
