= Dokumentenmanagementsystem (DMS)

xmera Omnia bietet mit dem Modul _DMS_ ein Dokumentenmanagementsystem, mit dem

- die Zugänglichkeit und Änderbarkeit von Dokumenten gesteuert,
- Dokumente strukturiert und klassifiziert, 
- Änderungen versioniert und  
- Freigaben über einen Genehmigungsworkflow organisiert und dokumentiert werden können.

NOTE: Das DMS Modul ist in jedem Objekt verfügbar und kann bei Bedarf aktiviert werden.

Zugriffssteuerung::

Dokumente, die für alle Mitarbeiter relevant sind, können in einem eigens dafür vorgesehenen Objekt zentral verwaltet und zugänglich gemacht werden. +
 +
Der Zugriff auf Dokumente, die dagegen nur für bestimmte Interessensgruppen relevant sind, kann durch eine entsprechende Rechtevergabe gesteuert werden. Das ist sowohl zentral als auch dezentral in Objekten, die als Arbeitsbereiche, Assets oder Projekte genutzt werden, möglich. +
 +
Durch zuordnen der Dokumente zu Ordnern sowie durch (administrativ erstellbare) Attribute lassen sich die Dokumente leicht strukturieren. Mit Hilfe von Verknüpfungen einzelner Dokumente zu anderen Elementen in xmera Omnia können Dokumente übergreifend den berechtigten Nutzern zugänglich gemacht werden.

Versionierung:: 

Zentraler Bestandteil des DMS ist die Versionierung. Dokumente, die mit ihren Metadaten erfasst wurden, können nicht direkt verändert werden. Änderungen müssen in einer neuen Version erfolgen. Damit ist eine Änderungsverfolgung jeder Änderung des Dokuments einschließlich seiner Metadaten möglich. +
Zusätzlich können Dokumente auch vor ungewollten Änderungen geschützt werden.

Genehmigungsworkflow:: Das DMS in xmera Omnia bietet die Möglichkeit, die Freigabe von Dokumenten über einen Genehmigungsworkflow durchzuführen und zu dokumentieren. +
 +
Ein Genehmigungsworkflow beschreibt den Ablauf des Freigabeprozesses. In xmera Omnia können verschiedene Freigabeprozesse (z.B. für Richtlinien, Handlungsanweisungen oder Betriebhandbücher) abgebildet werden. 
