= Wiki

In jedem Objekt in xmera Omnia kann das Modul _Wiki_ aktiviert werden. Dieses bietet alle Funktionalitäten eines Wiki. Es ermöglicht Informationen und Wissen kollaborativ zu bearbeiten und zu benutzen. Es eignet sich im Umfeld des ISMS, um Handbücher bereitzustellen oder auch Prozess- / Handlungsbeschreibungen zu einem Objekt zu dokumentieren.

Drawio Integration::
xmera Omnia unterstützt das Erstellen von Diagrammen und Flowcharts, die in das Wiki integriert werden können. So erstellen Sie leicht verständliche Prozessablaufpläne, bspw. im Rahmen des Notfallmanagement. Auch Netzpläne sind mit Hilfe der zahlreichen Bibliotheken zügig erstellt.

Interne Links / Makros:: 
Mit Hilfe von internen Verlinkungen und Makros lassen sich Inhalte aus anderen Modulen wie z.B. Dokumente, Aufgaben oder Wikiseiten aus anderen Objekten in einem Wiki übersichtlich zusammenfassen. 

Historie:: 
Die Historie zeigt alle Änderungen inkl. dem Bearbeiter und Zeitpunkt, die im Wiki durchgeführt wurden. In Kombination mit dem Berechtigungssystem, in dem die Rechte zur Bearbeitung definiert werden können, ist die Dokumentation revisionierbar.
