= Geschäftsprozesse und Informationen
:doctype: article
:icons: font
:imagesdir: ../images/
:web-xmera: https://xmera.de

include::ROOT:partial$custom-css.adoc[]

== Warum sind Geschäftsprozesse und Informationen zu analysieren?

Ziel der DIN ISO/IEC 27001 ist es, die Informationswerte einer Organisation zu schützen. Dafür müssen zunächst einmal die zu schützenden Informationswerte identifiziert werden. 

Das gelingt am besten mit Hilfe einer Analyse der wichtigsten Geschäftsprozesse, da sie die zu schützenden Informationswerte verarbeiten. Der Schutzbedarf dieser Informationen (primäre Assets) bildet die Basis für den Schutzbedarf der an der Informationsverarbeitung beteiligten Assets (sekundäre Assets).

== Wie unterstützt xmera Omnia?

include::shared:geschaeftsprozesse-informationen/geschaeftsprozesse.adoc[leveloffset=2]

include::shared:geschaeftsprozesse-informationen/informationen.adoc[leveloffset=2]

== Wo finde ich Beispiele in der Demo?

=== Prozesse

video::prozessobjekt.mp4[width=950]

=== Informationen

video::informationsobjekt.mp4[width=950]
