= Schritt 5 » IT-Servicemanagementprozesse
:doctype: article
:icons: font
:web-xmera: https://docs.xmera.de

include::ROOT:partial$custom-css.adoc[]

== Was ist in Schritt 5 umzusetzen?

Die IT-Servicemanagementprozesse beschreiben die Gesamtheit der Maßnahmen, die für den sicheren Betrieb der IT benötigt werden. Das beinhaltet

- die Wartungprozesse,
- die Störungsprozesse und
- die Änderungsprozesse.

Das Management ist an die Größe der Organisation anzupassen. In diesem Zusammenhang ist auch das Lieferantenmanagement, insbesondere im Zusammenhang mit dem Outsourcing von ID-Diensten, zu betrachten.

== Wie unterstützt xmera Omnia?

xmera Omnia unterstützt das IT-Servicemanagement in vielfältiger Weise. 

Die Wartungs- und Störungsprozesse können durch das Aufgaben/Ticket-Management gesteuert werden.

Bei komplexeren Change-/Änderungsprozessen bietet sich das in xmera Omnia integrierte Projektmanagement an.

include::shared:it-servicemanagement/vorfallmanagement.adoc[leveloffset=2]

include::shared:it-servicemanagement/ticketsystem.adoc[leveloffset=2]

include::shared:sonstiges/projekt-management.adoc[leveloffset=2]

== Wo finde ich Beispiele in der Demo?
