= Schritt 0-3 » CISIS 12 Start
:doctype: article
:icons: font
:web-xmera: https://docs.xmera.de

include::ROOT:partial$custom-css.adoc[]

== Was ist in den Schritten 0-3 umzusetzen?

Der *Schritt 0* beschreibt in CISIS 12 die Vorbereitungen für das Implementierungsprojekt. Hierzu sind für die Einführung eines ISMS
- der Projektauftrag,
- die Rollen,
- die Ziele,
- die Projektplanung und
- die Kommunikationsstruktur 
festzulegen. Dabei ist für ein ISMS nach CISIS 12 die Anwendbarkeitserklärung (SOA) von zentraler Bedeutung. Sie definiert die Grenzen des Informationssicherheitsmanagementsystems.

In CISIS 12 helfen bei der Definition der SOA die Bausteingruppen. Nicht relevante Bausteingruppen können mit nachvollziehbarer Begründung ausgeschlossen werden.

Der *1. Schritt* ist die Erstellung einer Leitlinie, in die grundlegende Festlegungen wie z.B. die Verantwortlichkeiten oder der Geltungsbereich für das ISMS definiert sind. 

In *Schritt 2* geht es um die Sensibilisierung der Beschäftigten. Es sind Maßnahmen zu planen, die das Bewusstsein (Awareness) der MitarbeiterInnen für das Thema Informationssicherheit erhöhen.

In *Schritt 3* ist das ISMS-Team zu benennen, das den Aufbau, die Aufrechterhaltung und die Verbesserung der ISMS Prozesse verantwortet.

== Wie unterstützt xmera Omnia?

include::shared:cisis12/cisis12_projekt.adoc[leveloffset=2]

include::shared:cisis12/cisis12_bausteine.adoc[leveloffset=2]

include::shared:isms-planung-bewertung/anwendbarkeitserklaerung.adoc[leveloffset=2]

include::shared:dokumente/dms.adoc[leveloffset=2]

== Wo finde ich Beispiele in der Demo?

* Projektplanung

* SOA

* DMS
