site:
  title: xmera Omnia Demo Guide
  url: /
  start_page: xmera-omnia-demo-guide:einfuehrung:index.adoc

content:
  sources:
  - url: .
    branches: HEAD
    start_path: .

ui: 
  bundle: 
    url: https://github.com/xmera-circle/antora-ui-omnia/releases/download/0.2.3/ui-bundle.zip
    snapshot: true

antora:
  extensions:
  - require: '@antora/lunr-extension'
