= Vorfallmanagement
:doctype: article
:icons: font
:web-xmera: https://xmera.de

== Wofür wird Vorfallmanagement benötigt?

Die ISO 27001 gibt im Anhang A Vorgaben, wie eine Organisation mit Informationssicherheitsvorfällen umzugehen hat. Dieses beinhaltet

- die Beschreibung des Verfahrens
- einen etablierten Meldeprozess
- eine zügige Bearbeitung und Beurteilung der Meldungen
- eine dem Vorfall entsprechende Reaktion
- eine Analyse und Lösungen der Vorfälle

== Wie unterstützt xmera Omnia?

xmera Omnia unterstützt den gesamten Prozess des Vorfallmanagements. Dieser geht von der automatisierten Zuordnung von Meldungen zu Mitarbeiten oder Gruppen, die Priorisierung und Gruppierung sowie die Analyse des Vorfalls.

Automatisieren:: 

In der xmera Omnia Demo ist die Meldungserfassung abgebildet. Meldungen können, wie auch Aufgaben, automatisch einem Bearbeiter oder einer Bearbeitergruppe zugewiesen werden. Auch eine automatischer Mailversand ist mit der Erstellung möglich. +

[NOTE]
Besteht bereits ein Ticketsystem kann über eine Mail- oder API-Schnittstelle xmera Omnia mit diesem verknüpft werden.
 +

Priorisieren und Gruppieren:: 

Die einlaufende Meldung kann je nach Beurteilung anschließend als Aufgabe, Störung oder Vorfall eingestuft werden. Dieser können dann noch Unteraufgaben zugeordnet werden. +
+
Weiter lassen sich diese über die Priorisierung und Kategorisierung der Vorfall weiter strukturieren. Durch Verknüpfungen zu anderen Vorfällen lassen sich auch ähnliche Vorfälle verknüpfen. +

[NOTE]
Über eigene Felder lassen sich leicht weitere Felder in eine Aufgabe integrieren und so an den Nutzer anpassen.

Analysieren:: 

Zur Analyse ist in der xmera Omnia die 5-W-Methode (5-Why-Methode nach Toyoda Sakichi) implementiert, in der in 5 Frageschritten der Vorfall aus verschiedenen Aspekten beleuchtet wird. Ziel ist es, Maßnahmen zu finden, die präventiv einen solchen Vorfall verhindern oder die Auswirkungen verringern. Diese Maßnahmen können wiederum als Unteraufgabe dem Vorfall zugeordnet werden.

== Wo finde ich Beispiele in der Demo?

...



