= Maßnahmenmangement
:doctype: article
:icons: font
:web-xmera: https://docs.xmera.de

include::ROOT:partial$custom-css.adoc[]

== Wofür wird das Maßnahmenmanagement benötigt?

Ein wesentlicher Bestandteil eines ISMS ist die Erklärung zur Anwendbarkeit (Statement of Applicability | SOA), in der die Sicherheitsanforderungen zusammengefasst werden, die zur Erreichung der Sicherheitsziele der Organisation relevant sind. Der Katalog der Sicherheitsanforderungen ist dem Anhang A der DIN ISO/IEC 27001 zu entnehmen.

Die sich aus den Anforderungen ergebenden Maßnahmen werden ergänzt um weitere Maßnahmen aus

- eigenen Sicherheitsstandards,
- der Risikobewertung,
- der Vorfallanalyse oder
- internen wie externen Audits.

Die Umsetzung der Maßnahmen ist zu überwachen und ihr Umsetzungsgrad zu ermitteln.

[NOTE]

xmera Omnia bietet den Anforderungskatalog als Importpaket gemäß DIN ISO/IEC 27001 Anhang A an, der um individuelle Anforderungen erweitert werden kann.

== Wie unterstützt xmera Omnia?

Erklärung zur Anwendbarkeit (SOA):: 

Der Anforderungskatalog kann an zentraler Stelle importiert und verwaltet werden. Von dort aus können die Sicherheitsanforderungen durch eine automatische Zuordnung (Synchronisieren) zu zugehörigen Assets innerhalb des Informationsverbundes verteilt werden. So werden z.B. einem Server nur die Anforderungen zugeordnet, die für den Serverbetrieb relevant sind. +
+
Sicherheitsanforderungen, die für die Organisation nicht relevant sind, müssen mit einer Begründung dokumentiert werden. Die Anwendbarkeitserklärung kann zur weiteren Verarbeitung oder Vorlage beim Auditor exportiert werden.

Status und Umsetzungsgrad:: 

Aus dem Anforderungskatalog sind Maßnahmen abzuleiten, zu planen, zu deligieren und zu überwachen. Zu jeder Maßnahme lassen sich Status und Umsetzungsgrad vom Verantwortlichen angeben, wodurch der Informationssicherheitsbeauftragte jederzeit einen Überblick über den Fortschritt erhält.  +
+
Auswertungen kann er sowohl auf Ebene eines einzelnen Assets vornehmen als auch auf der Ebene von übergeordneten Objekten. In der obersten Ebene erhält er einen Überblick über das gesamte System.  +
+
Um die Übersichtlichkeit zu erhöhen, lassen sich _Aufgabenpakete_ bilden. Sie fassen Maßnahmen und zugehörige Aufgaben zusammen. Auch bei Aufgabenpaketen werden unterlagerte Maßnahmen und Aufgaben kumuliert dargestellt, so dass auch hier leicht ein Umsetzungsgrad überwacht werden kann.

Tabellarische und graphische Auswertung:: 

Zur Priorisierung und Umsetzungsüberwachung bietet xmera Omnia vielfältige Möglichkeiten der Datenauswertung. Dabei unterstützen Filterfunktionen und eine flexible Spaltenanordnung innerhalb der Tabellen. Zusätzliche graphische Auswertungen runden die Analyse ab.

== Wo finde ich Beispiele in der Demo?

=== Anwendbarkeitserklärung

video::massnahmen_soa.mp4[width=950]

=== Maßnahmen-Synchronisierung

video::massnahmen_synchronisierung.mp4[width=950]

=== Aufgabenpakete

video::massnahmen_pakete.mp4[width=950]

=== Graphische Auswertung

video::massnahmen_diagramme.mp4[width=950]
