= Assetregister
:doctype: article
:icons: font
:imagesdir: ../images/
:web-xmera: https://xmera.de

== Wofür wird das Assetregister benötigt?

Die DIN ISO/IEC 27001 fordert die Verwaltung der Werte (Assets) der Organisation. Dabei sind die Geschäftsprozesse und Informationen (primäre Assets) sowie die informationsverarbeitenden Einrichtungen (sekundäre Assets), die im Zusammenhang mit den Informationen stehen, zu inventarisieren.

Zu den sekundären Assets gehören zum Beispiel:

* Software, 
* Hardware, 
* Kommunikationssysteme,
* Infrastruktur. 



== Wie unterstützt xmera Omnia?

Zu den wesentlichen Merkmalen gehören:

Verwaltung von Assets:: 

Assets werden in xmera Omnia als Objekte erfasst. Diese Objekte können hierarchisch strukturiert werden. So können über den Hierarchiebaum die Aufbauorganisation und damit Verantwortlichkeiten der Organisation abgebildet werden. Alternativ könnten Assets mit gleichem Schutzbedarf analog zu räumlichen Sicherheitszonen im Hierarchiebaum zusammengefasst werden.

Logische Strukturen abbilden:: 

Neben den hierarchischen Strukturen können auch logische Verknüpfungen (Zusammenhänge zwischen den Objekten) abgebildet werden. +
+
Objektverknüpfungen bilden die Basis für die Vererbung des Schutzbedarfs, der in der xref:xo-quick-guide_sbf.adoc[Schutzbedarfsanalyse] auf Ebene der Informationsobjekte oder Geschäftsprozesse ermittelt wird. +
+
[NOTE] 
.Beispiel einer Vererbungskette
====
Informationen -> werden in einer _Anwendung_ gepflegt -> die auf einem _Server_ läuft -> der in einem _Serverraum_ -> in einem _Werksgebäude_ steht.
====

Verantwortlichkeiten zuordnen:: 
Den Assets können Mitarbeiter zugeordnet werden. Jeder Mitarbeiter kann in der für ein spezifisches Asset passenden Rolle hinzugefügt werden. Dabei stehen die Rollen zur Verfügung, die über das Berechtigungsmanagement vom Administrator angelegt wurden. In der Demo sind das beispielsweise der Objektverantwortliche, Aufgabenverantwortliche, Risikoverantwortliche oder Beobachter. 

== Wo finde ich Beispiele in der Demo?
pass:[<style>
.distance-25 { 
  display:block;
  height:25px;
}
.flex-container {
  display:flex;
  justify-content:center;
  flex-wrap: wrap;
}
.video-container {
  flex: 0 0 100%;
  margin-top: 30px;
  margin-bottom: 50px;
}
.center { 
  text-align:center;
}
video { 
  -webkit-box-shadow: 0 2px 8px 0 rgba(31,32,68,.16);
  -webkit-transition: all .7s cubic-bezier(.23,1,.32,1);
  transition: all .7s cubic-bezier(.23,1,.32,1);
  box-shadow: 0 2px 8px 0 rgba(31,32,68,.16);
  border-color: #f3f4f4;
}
</style>]

pass:[<span class="distance-25"></span>]

TIP: Das Assetregister ist von jeder Seite aus über das Top-Menü unter dem Menüelement *Objekte* erreichbar.

pass:[<span class="distance-25"></span>]

### Verwaltung von Assets

pass:[
<div class="flex-container">
  <div class="video-container center">
    <video src="_images/assetregister_objekthierarchie.mp4" type="video/mp4" controls width="950">
    Your browser does not support HTML video.
    </video>
  </div>
</div>
]

### Logische Strukturen abbilden

pass:[
<div class="flex-container">
  <div class="video-container center">
    <video src="_images/assetregister_objektverknuepfungen.mp4" type="video/mp4" controls width="950">
    Your browser does not support HTML video.
    </video>
  </div>
</div>
]

### Verantwortlichkeiten zuordnen

pass:[
<div class="flex-container">
  <div class="video-container center">
    <video src="_images/assetregister_verantwortlichkeiten.mp4" type="video/mp4" controls width="950">
    Your browser does not support HTML video.
    </video>
  </div>
</div>
]
