= Vorfallmanagement
:doctype: article
:icons: font
:web-xmera: https://docs.xmera.de

include::ROOT:partial$custom-css.adoc[]

== Wofür wird das Vorfallmanagement benötigt?

Die DIN ISO/IEC 27001 macht im Anhang A Vorgaben, wie eine Organisation mit Informationssicherheitsvorfällen umzugehen hat. Dieses beinhaltet

- die Beschreibung des Verfahrens,
- einen etablierten Meldeprozess,
- eine zügige Bearbeitung und Beurteilung der Meldungen,
- eine dem Vorfall entsprechende Reaktion,
- eine Analyse und Lösungen der Vorfälle.

== Wie unterstützt xmera Omnia?

xmera Omnia unterstützt den gesamten Prozess des Vorfallmanagements. Dazu gehört die automatisierte Zuordnung von eingehenden Meldungen zu einzelnen Mitarbeiten oder Gruppen, die Priorisierung und Gruppierung sowie die Analyse des Vorfalls.

Automatisieren:: 

In der xmera Omnia Demo ist die Meldungserfassung abgebildet. Meldungen können, wie auch Aufgaben, automatisch einem Bearbeiter oder einer Bearbeitergruppe zugewiesen werden. Die Erstellung einer Meldung kann im System selbst erfolgen oder per E-Mail an das System gesendet werden. Der E-Mail-Empfang ist in der Testinstanz nicht verfügbar. +

[TIP]
Besteht bereits eine Lösung für das Vorfallmangement (z.B. Ticketsystem) kann über die E-Mail- oder API-Schnittstelle von xmera Omnia wohlmöglich eine Kopplung der Systeme erreicht werden.
 +

Priorisieren und Gruppieren:: 

Die einlaufende Meldung kann je nach Beurteilung anschließend als Aufgabe, Störung oder Vorfall eingestuft werden. Dieser können dann noch sich ergebende Unteraufgaben zugeordnet werden. +
+
Der Vorfall läßt sich über die Priorisierung und Kategorisierung weiter strukturieren. Durch Verknüpfungen zu anderen Vorfällen lassen sich auch ähnliche Vorfälle zusammenfassen. +

[NOTE]
Über die Funktion _Eigene Felder_ lassen sich leicht weitere Felder in eine Aufgabe integrieren und so an den Nutzer anpassen.

Analysieren:: 

Zur Analyse ist in xmera Omnia die 5-W-Methode (5-Why-Methode nach Toyoda Sakichi) implementiert. Dabei wird in 5 Frageschritten der Vorfall aus verschiedenen Aspekten beleuchtet. Ziel ist es, Maßnahmen zu finden, die präventiv einen solchen Vorfall verhindern oder die Auswirkungen verringern. Diese Maßnahmen können wiederum als Unteraufgabe dem Vorfall zugeordnet werden.

== Wo finde ich Beispiele in der Demo?

=== Erfassung

video::vorfall_erfassung.mp4[width=950]

=== Analyse

video::vorfall_analyse.mp4[width=950]
