= Risikobeurteilung
:doctype: article
:icons: font
:web-xmera: https://docs.xmera.de

include::ROOT:partial$custom-css.adoc[]

== Wofür wird die Risikobeurteilung benötigt?

Ein weiteres zentrales Element eines ISMS ist die Informationssicherheitsbeurteilung. Hat ein Asset einen Schutzbedarf, der eine weitergehende Analyse erfordert (zumeist _Hoch_ oder _Sehr Hoch_), so ist eine Risikobewertung durchzuführen. 

Gegenstand der Bewertung sind die Einschätzung der Eintrittswahrscheinlichkeit und der Schadenhöhe für ein sicherheitsrelevantes Ereignis. Der berechnete Wert ist das aktuelle Risiko für das vorliegende Ereignis. 

Dieses Risiko wird dem Risikoappetit der Organisation gegenüber gestellt. Anhand der Risikoakzeptanzmatrix wird über die Risikobehandlung des zugrunde liegenden Ereignisses entschieden. Die sich daraus ergebenden Maßnahmen sind zu definieren und zu priorisieren.

== Wie unterstützt xmera Omnia?

Gefährdungen:: 

Basis für die Risikobeurteilung in xmera Omnia sind Gefährdungen (Bedrohung + Schwachstelle). Gefährdungen beschreiben die möglichen Gefahrenquellen, denen ein Asset ausgesetzt sein kann. +
+
[NOTE]

xmera Omnia bietet ein Importpaket des Gefährdungskataloges gemäß DIN ISO/IEC 27005 an, das um individuelle Gefährdungen erweitert werden kann.

+
Die Risikobewertung, die gewählte Risikobehandlungsoption und das sich daraus ergebende neue Risikoniveau lassen sich ebenfalls in der Risikobeurteilung abbilden. +
+
Wird eine Maßnahme erforderlich, kann diese direkt erstellt und mit der Risikobeurteilung verknüpft werden.

Risikoakzeptanzmatrix:: 

Für die Ermittlung des Risikoniveaus wird in xmera Omnia eine individuell konfigurierbare Risikoakzeptanzmatrix bereitgestellt, in der für jede Kombination aus Eintrittshäufigkeit und Schadensklasse ein Risikoniveau zugeordnet werden kann. In der Demo wird hierfür eine 4 x 4 Matrix verwendet, woraus sich 16 Kombinationen ergeben.

NOTE: Da die Konfiguration der Risikoakzeptanzmatrix im Administrationsbereich vorgenommen werden muss, ist dies im Rahmen der Demo nicht möglich.

Risikobehandlungsplan:: 
Wird ein Risikoniveau durch eine Maßnahme reduziert oder vermieden, so kann die Maßnahmen als Unteraufgabe an die Gefährdung gekoppelt werden. Alle Maßnahmen, die aus einer Risikobeurteilung erwachsen sind, können dann in einem Risikobehandlungsplan zusammengefasst werden. Dieser Risikobehandlungsplan zeigt alle Maßnahmen, die als Ziel haben, dass Schutzniveau auf ein akzeptables Maß zu bringen.

== Wo finde ich Beispiele in der Demo?

NOTE: Videos zu diesem Thema folgen in Kürze!
