= CISIS12 Bausteine

Die Bausteine aus CISIS12 sind in xmera Omnia integriert. Die *Bausteine aus der CISIS12-Norm* sind mit dem Sicherheitsziel als übergeordnete Sicherheitsanforderung im System abgebildet. +
Die einzelnen *Maßnahmen* zur Erreichung der Sicherheitsziel *aus dem CISIS12-Katalog* sind dem Baustein als untergeordnete Sicherheitsanforderungen zugeordnet. Es sind die Anforderungen, Umsetzungshinweise und der Verweis aus die Verantwortlichkeiten integriert. Auch die Relevanz der Maßnahme (MUSS, SOLL, KANN) ist als filter / sortierbares Element enthalten.

Mit diesen Informationen hat jeder Maßnahmenverantwortliche alle relevanten Informationen aus dem CISIS12 direkt im Zugriff und kann so die Maßnahmen zielgerichtet umsetzen. Weiter wird

- durch die Gliederung nach Bausteinen (z.B. in der Anwendbarkeitserklärung) und
- die Filterung / Sortierung nach der Relevanz

die Übersichtlichkeit erheblich verbessert werden.

Die Bausteine / Maßnahmen werden weiter zur automatisierten Zuordnung der Sicherheitsanforderungen an die relevanten Assets genutzt.