= Einführung in die xmera Omnia Demo
:doctype: article
:icons: font
:web-xmera: https://docs.xmera.de

xmera Omnia ist das zentrale Element in Ihrem Informationssicherheits- und Datenschutzmanagementsystem. Es liefert Ihnen jederzeit einen umfassenden Einblick über Ihre Managementprozesse und erleichtert die Zusammenarbeit mit Verantwortlichen und dem Auditor.

Um unsere Software auf Basis von Demodaten online zu testen, bieten wir Testinstanzen an. Auf diese Weise können Sie das System auf eigene Faust erkunden.

Vorab empfehlen wir eine persönliche Vorführung des Systems. https://xmera.de/live-vorfuehrung/[Sprechen Sie uns dazu gerne an!]

== Allgemeines zur xmera Omnia Demo

Die xmera Omnia Demo soll Interessenten einen Einblick in die Möglichkeiten unserer ISMS Softwarelösung xmera Omnia geben. 

Bei der Demo sind 3 Punkte zu beachten: 

1. Die Demo zeigt kein vollständig mit Daten befülltes ISMS, sondern einzelne Teilbereiche, anhand derer die Funktionalität von xmera Omnia verständlich wird. Dieser Guide führt Sie daher in kurzen Videosequenzen durch die mit Daten befüllten Bereiche, um diese gezielt in Ihrer Testinstanz aufsuchen zu können.

2. Als Benutzer in der Testinstanz haben Sie keine Administratorenrechte. Dadurch bleibt ein großer Bereich, in dem die Software individualisiert werden kann, für Sie verborgen. Beachten Sie daher auch Punkt 3.

3. Die Software xmera Omnia lebt den Anspruch, dass Softwareprozesse flexibel an Unternehmensprozesse angepasst werden können sollten. Die dargestellten Lösungen der fiktiven Demo GmbH zeigen damit *einen* Weg auf, ISMS-Prozesse abzubilden. Wenn ein dargestellter Prozess nicht Ihren Anforderungen genügt, wenden Sie sich gerne an uns. In einem persönlichen Gespräch zeigen wir Ihnen geeignete Individualisierungsmöglichkeiten auf.

== Der xmera Omnia Demo Guide

Dieser Demo-Guide soll Ihnen den Einstieg in die xmera Omnia Demo und deren Funktionalität erleichtern. Dabei werden für die verschiedenen ISMS Standards (DIN ISO/IEC 27k, CISIS 12) unterschiedliche Demos angeboten. Das hat den Vorteil, dass sich Interessenten, die bereits Erfahrungen in einem der Standards haben, leichter orientieren und sich gezielt informieren können.

In der Einleitung werden grundlegende Informationen zur Nutzung der jeweiligen Demo gegeben. Alle Erläuterungen beziehen sich auf **xmera Omnia 3.6**.

* xref:isms-iso-27k:index.adoc[27k Demo]
* xref:isms-cisis-12:index.adoc[CISIS 12 Demo]

In den untergeordneten Seiten folgt für jedes Funktionsmodul eine eigene Beschreibung.
