= Import / Export

xmera Omnia bietet verschiedene Schnittstellen an, die den Austausch mit externen Systemen oder Personen ermöglichen.

PDF-Export:: 

Der PDF-Export bietet die Möglichkeit Aufgaben-Listen, den Verlauf oder Wiki-Seiten als PDF-Datei herunterzuladen. +
+
[NOTE]
Wiki-Seiten können auch als html-Datei oder txt-Datei heruntergeladen werden.

CSV-Schnittstelle:: 

Die CSV-Schnittstelle ermöglicht einen manuellen Austausch von Listen. *Exportiert* werden können die Abfrage-Listen der Objekte und Aufgaben. Dabei ist eine individuelle Anpassung der zu übertragenden Attribute möglich. +
+
Die *CSV-Importschnittstelle* ermöglicht es Aufgaben zu importieren. Das können Maßnahmenkataloge aus eigenen Vorgaben oder anderen Standards oder auch Aufgaben aus einem anderen Ticket-Systemen sein, die in das System integriert werden sollen. 

API / E-Mail Schnittstelle:: 

Dynamischer sind dabei die Online-Schnittstellen wie die E-Mail-Kopplung oder die API, über die dynamisch externe Systeme integriert werden können. +
+
Die *E-Mail-Schnittstelle* ermöglicht es, eingehende E-Mails in eine Aufgabe (Ticket) zu wandeln. Bei der Einhaltung der Format-Regeln, können die E-Mails konkreten Objekten und definierten Aufgabentypen zugeordnet werden. +
+
Die API-Schnittstelle in xmera Omnia ermöglicht einen Datenaustausch bei Objekten, Aufgaben und Benutzern. Dabei wird das Anlegen, Ändern, Löschen oder auch Archivieren unterstützt. Die API-Schnittstelle unterstützt dabei sowohl das xml- als auch json-Format.
