= Import / Export

xmera Omnia bietet verschiedene Schnittstellen an, die den Austausch mit externen Systemen oder Personen ermöglicht.

PDF-Export:: 

Der PDF-Export bietet die Möglichkeit Aufgaben-Listen, den Verlauf oder Wiki-Seiten als PDF-Datei herunterzuladen. +
+
[NOTE]
Wiki-Seiten können auch als html-Datei oder txt-Datei heruntergeladen werden.

csv-Schnittstelle:: 

Die csv-Schnittstelle ermöglicht einen manuellen Austausch von Listen. *Exportiert* werden können die Abfrage-Listen der Objekte und Aufgaben. Dabei ist eine individuelle Anpassung der Übertragenen Attribute möglich. +
+
Die *csv-Importschnittstelle* ermöglicht es Aufgaben zu importieren. Das können Maßnahmenkataloge aus eigenen Vorgaben oder anderen Standards sein oder auch Aufgaben aus einem anderen Ticket-System sein, die in das System integriert werden sollen. 

API / E-Mail Schnittstelle:: 

Dynamischer sind dabei die Online-Schnittstellen über die E-Mail-Kopplung oder die API-Schnittstelle über die dynamisch externe Systeme integriert werden können. +
+
Die *E-Mail-Schnittstelle* ermöglicht es, eingehende E-Mails in eine Aufgabe (Ticket) zu wandeln. Bei der Einhaltung der Format-Regeln, können sie Mails konkreten Objekten und definierten Aufgabentypen zugeordnet werden. +
+
Die API-Schnittstelle in xmera Omnia ermöglicht eine Datenaustausch bei Objekten, Aufgaben und Usern. Dabei wird das Anlegen, Ändern, Löschen oder auch Archivieren unterstützt. Die API-Schnittstelle unterstützt dabei sowohl das xml- als auch json-Format.