= Schritt 6 » Compliance, Prozesse und Anwendungen
:doctype: article
:icons: font
:web-xmera: https://docs.xmera.de

include::ROOT:partial$custom-css.adoc[]

== Was ist in Schritt 6 umzusetzen?

Der Schritt 6 umfasst die Darstellung der Organisationsprozesse und die Analyse

- der einzuhaltenden Gesetzte und Richtlinien (Comliance)
- die Analyse der Prozessverfügbarkeit (Business Impact Analyse (BIA)) 
- die Analyse der Informationen in Bezug auf die Sicherheitsziele (Schutzbedarfsfeststellung (SBF))

Den kritischen Prozessen sind dann die notwendigen Anwendungen, IT-Assets und Infrastrukturen zuzuordnen.

== Wie unterstützt xmera Omnia?

xmera Omnia bietet über die Geschäftsprozessabbildung, die Informationen und die Schutzbedarfsfeststellung und die Zuordnung der benötigten Assets über die _Logische Struktur_ die Funktionalität zur Abbildung der in Schritt 6 geforderten Geschäftsprozessanalyse

include::shared:geschaeftsprozesse-informationen/geschaeftsprozesse.adoc[leveloffset=2]

include::shared:geschaeftsprozesse-informationen/informationen.adoc[leveloffset=2]

include::shared:schutzbedarfanalyse/schutzbedarffeststellung.adoc[leveloffset=2]

=== Logische Strukturen

Die logischen Strukturen in xmera Omnia bilden die abhängigkeiten der Objekte untereinander ab. In Schritt 6 können die Informationen mit den verarbeitenden Anwendungen, die benötigte IT-Infrastruktur oder auch mit der Gebäudeinfrastruktur verbunden werden. Nähers dazu in Schritt 7 » IT-Struktur analysieren .

== Wo finde ich Beispiele in der Demo?